const actionTypes = {
  END_FETCHING_DATA: 'END_FETCHING_DATA',
  SET_FILTER: 'SET_FILTER',
  SET_RECOMMENDED_LIST: 'SET_RECOMMENDED_LIST',
  SET_TOP_LIST: 'SET_TOP_LIST',
  START_FETCHING_DATA: 'START_FETCHING_DATA',
};

export default actionTypes;
